In [1]:
# going to import the necessary packages 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.decomposition import PCA, TruncatedSVD as SVD
import plotly_express as px 
import plotly.io as pio

# Loading in the data

In [2]:
LIB = pd.read_csv('/Users/aniyahmcwilliams/Spring 2026/Text As Data/final project/DATA/LIB.csv', index_col='mag_id')
TFIDF = pd.read_csv('/Users/aniyahmcwilliams/Spring 2026/Text As Data/final project/DATA/TFIDF_L2.csv',index_col='mag_id')
TFIDF

,aaron,abandoned,abc,ability,able,aboard,abortion,above,abroad,abruptly,...,yourself,youthful,youthfullooking,youths,ypsilanti,yvonne,zion,zip,zone,zurich
mag_id,,,,,,,,,,,,,,,,,,,,,
0,0.000000,0.000000,0.010796,0.021591,0.018473,0.000000,0.000000,0.000000,0.014271,0.000000,...,0.007956,0.018752,0.000000,0.011110,0.025067,0.000000,0.014271,0.056255,0.000000,0.000000
1,0.016102,0.000000,0.012180,0.012180,0.000000,0.028282,0.000000,0.014228,0.000000,0.000000,...,0.008977,0.000000,0.028282,0.000000,0.000000,0.006268,0.016102,0.033533,0.000000,0.000000
2,0.000000,0.025162,0.017176,0.000000,0.000000,0.000000,0.014325,0.018543,0.000000,0.000000,...,0.020644,0.000000,0.000000,0.011152,0.000000,0.005576,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.033156,0.011052,0.012910,0.000000,0.000000,0.008145,0.000000,0.014610,...,0.008145,0.000000,0.025662,0.005687,0.025662,0.005687,0.000000,0.019197,0.000000,0.000000
4,0.000000,0.000000,0.027526,0.010649,0.015695,0.000000,0.014077,0.000000,0.000000,0.000000,...,0.007848,0.000000,0.000000,0.000000,0.000000,0.008685,0.000000,0.000000,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.000000,0.008283,0.000000,0.023547,0.000000,0.014857,0.014857,...,0.000000,0.000000,0.000000,0.005783,0.000000,0.000000,0.023547,0.000000,0.014857,0.000000
6,0.030687,0.000000,0.000000,0.000000,0.013558,0.000000,0.000000,0.000000,0.015344,0.000000,...,0.008554,0.000000,0.000000,0.009466,0.000000,0.005973,0.000000,0.000000,0.000000,0.024319
7,0.043201,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.013597,0.024390,0.015388,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.005990,0.000000,0.000000,0.015388,0.015388
8,0.014931,0.026227,0.000000,0.011295,0.000000,0.026227,0.014931,0.008324,0.000000,0.014931,...,0.000000,0.019619,0.000000,0.015024,0.000000,0.000000,0.000000,0.000000,0.029863,0.014931
9,0.000000,0.000000,0.000000,0.000000,0.013338,0.000000,0.000000,0.013338,0.000000,0.000000,...,0.000000,0.019835,0.000000,0.011752,0.000000,0.005876,0.015096,0.000000,0.023926,0.015096

# PCA Models

## Generating the Document Component Matrix

In [3]:
pca_engine = PCA(n_components=3)
DCM = pd.DataFrame(pca_engine.fit_transform(TFIDF), index=TFIDF.index)
DCM.columns = ['PC{}'.format(i) for i in DCM.columns]
DCM

/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:350: RuntimeWarning: divide by zero encountered in matmul
  Q, _ = normalizer(A @ Q)
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:350: RuntimeWarning: overflow encountered in matmul
  Q, _ = normalizer(A @ Q)
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:350: RuntimeWarning: invalid value encountered in matmul
  Q, _ = normalizer(A @ Q)
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:351: RuntimeWarning: divide by zero encountered in matmul
  Q, _ = normalizer(A.T @ Q)
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:351: RuntimeWarning: overflow encountered in matmul
  Q, _ = normalizer(A.T @ Q)
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:351: RuntimeWarning: invalid value encountered in matmul
  Q, _ = normalizer(A.T @ Q)
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:355: RuntimeWarning: divide by zero encountered in matmul
  Q, _ = qr_normalizer(A @ Q)
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:355: RuntimeWarning: overflow encountered in matmul
  Q, _ = qr_normalizer(A @ Q)
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:355: RuntimeWarning: invalid value encountered in matmul
  Q, _ = qr_normalizer(A @ Q)
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:577: RuntimeWarning: divide by zero encountered in matmul
  B = Q.T @ M
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:577: RuntimeWarning: overflow encountered in matmul
  B = Q.T @ M
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:577: RuntimeWarning: invalid value encountered in matmul
  B = Q.T @ M
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:590: RuntimeWarning: divide by zero encountered in matmul
  U = Q @ Uhat
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:590: RuntimeWarning: overflow encountered in matmul
  U = Q @ Uhat
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:590: RuntimeWarning: invalid value encountered in matmul
  U = Q @ Uhat

             PC0       PC1       PC2
mag_id
0       0.273132  0.320992  0.141877
1       0.112682  0.589440  0.086176
2       0.332278 -0.084580  0.062886
3       0.452878 -0.241581 -0.105051
4       0.394794 -0.250561 -0.229338
5      -0.220825 -0.211008  0.726553
6      -0.362469  0.295010 -0.156411
7      -0.352970 -0.226305 -0.244103
8      -0.307104  0.071027 -0.311315
9      -0.322398 -0.262435  0.028725

The number of components is 3.

## Component Term Matrix

In [4]:
COMPS = pd.DataFrame(pca_engine.components_.T * np.sqrt(pca_engine.explained_variance_))
COMPS.columns = ["PC{}".format(i) for i in COMPS.columns]
COMPS.index = TFIDF.columns
COMPS.index.name = 'term_str'
COMPS.T

term_str,aaron,abandoned,abc,ability,able,aboard,abortion,above,abroad,abruptly,...,yourself,youthful,youthfullooking,youths,ypsilanti,yvonne,zion,zip,zone,zurich
PC0,-0.009428,0.000099,0.011618,0.004209,0.001956,-0.001575,0.000172,-0.000066,-0.004385,-0.002161,...,0.004442,-0.002361,0.004791,-0.001228,0.005975,0.000773,-0.001409,0.009006,-0.008281,-0.007667
PC1,0.003584,-0.000097,-0.002084,0.003492,-0.000864,0.006759,-0.003153,-0.000414,0.000165,-0.003314,...,0.001710,0.000805,0.003819,0.000293,0.000673,-0.000533,0.001875,0.012102,-0.003930,0.000288
PC2,-0.006913,-0.002446,-0.002279,-0.001117,0.000723,-0.002128,0.003765,-0.001483,0.001659,0.000318,...,-0.000295,-0.001069,-0.000096,0.000023,0.000320,-0.001459,0.007786,0.003290,-0.000584,-0.004375

### Getting the top 5 positive and negative terms

In [5]:
top_terms = []
data = []
for i in range(3):
    for j in [0, 1]:
        comp_str = ' '.join(COMPS.sort_values(f'PC{i}', ascending=bool(j)).head(5).index.to_list())
        top_terms.append((f"PC{i}", j, comp_str))
        
COMP_GLOSS = pd.DataFrame(top_terms).set_index([0,1]).unstack()
COMP_GLOSS.index.name = 'comp_id'
COMP_GLOSS.columns = COMP_GLOSS.columns.droplevel(0) 
COMP_GLOSS = COMP_GLOSS.rename(columns={0:'positive', 1:'negative'})
COMP_GLOSS.columns.name = 'polarity'
COMP_GLOSS

polarity,positive,negative
comp_id,,
PC0,blacks reggie ali mg ms,dinah satchel wealthy ark doby
PC1,supremes bourbon campus ferguson facial,reggie ruby doby watson mg
PC2,mink tobias apollo yards dress,dinah grass sarah nkrumah soviet

In [6]:
# converting everyting into a dataframe to download as a csv 
DCM_df = pd.DataFrame(DCM) # document-component matrix 
COMP_df = pd.DataFrame(COMPS.T) #component-term matrix 
COMP_top_terms = pd.DataFrame(COMP_GLOSS) # top terms
# print(DCM_df)
# print(COMP_df)
# print(COMP_top_terms)

## Saving everything as a csv

In [7]:
# DCM_df.to_csv('/Users/aniyahmcwilliams/Spring 2026/Text As Data/final project/PCA/DCM.csv')
# COMP_df.to_csv('/Users/aniyahmcwilliams/Spring 2026/Text As Data/final project/PCA/COMP.csv')
# COMP_top_terms.to_csv('/Users/aniyahmcwilliams/Spring 2026/Text As Data/final project/PCA/COMP_top_terms.csv')

# PCA Visualizations

In [8]:
LIB

,epub_id,date,pages,month,quarter,page_num,title,character_len
mag_id,,,,,,,,
0,vo8DAAAAMBAJ,1972-12-07,"[""\n\n\n\nThis book was produced in EPUB forma...",12,4th Quarter,68,What Dope Arrest is Doing to Career of Barbara...,99374
1,ProDAAAAMBAJ,1967-05-11,"[""\n\n\n\nThis book was produced in EPUB forma...",5,2nd Quarter,68,What's Behind Suicide of Charles Diggs Sr.?,74986
2,dEIDAAAAMBAJ,1975-11-20,"[""\n\n\n\nThis book was produced in EPUB forma...",11,4th Quarter,68,Tito Jackson: His Music and His Family,89009
3,YEIDAAAAMBAJ,1978-05-04,"[""\n\n\n\nThis book was produced in EPUB forma...",5,2nd Quarter,68,New Reggie Defends His Hero Image,85341
4,AMADAAAAMBAJ,1978-07-06,"[""\n\n\n\nThis book was produced in EPUB forma...",7,3rd Quarter,68,Benson Shares His Fame With Family,89396
5,JEMDAAAAMBAJ,1951-11-01,"[""\n\n\n\nThis book was produced in EPUB forma...",11,4th Quarter,68,Ten Ways to Get a Mink Coat/ Why Negro Suicide...,81741
6,vq8DAAAAMBAJ,1960-03-10,"[""\n\n\n\nThis book was produced in EPUB forma...",3,1st Quarter,68,How Negroes Feel about a Catholic for US Presi...,79252
7,fbcDAAAAMBAJ,1958-02-20,"[""\n\n\n\nThis book was produced in EPUB forma...",2,1st Quarter,68,Rudy McCollum Talks Ends 5-Year Silence in Ins...,74909
8,YkEDAAAAMBAJ,1959-08-20,"[""\n\n\n\nThis book was produced in EPUB forma...",8,3rd Quarter,68,First Poll Reveals Candidates Negroes Want for...,78302
9,mEEDAAAAMBAJ,1959-04-09,"[""\n\n\n\nThis book was produced in EPUB forma...",4,2nd Quarter,68,Why Cuban Rebels Jailed Son of Wealthy Negro /...,76401

In [9]:
def vis_pcs(DCM, a, b, label = 'quarter', hover_name='title'):
    return px.scatter(DCM, f"PC{a}", f"PC{b}",  
                    color=LIB[label],
                    hover_name=LIB[hover_name], 
                    size=LIB['character_len'],
                    marginal_x='box', height=800)
    
def vis_loadings(COMPS, a=0, b=1, hover_name='term_str'):
    return px.scatter(COMPS.reset_index(), f"PC{a}", f"PC{b}", 
                      text='term_str', 
                      marginal_x='box', 
                      height=800)

In [10]:
vis_pcs(DCM, 0, 1)

In [11]:
vis_loadings(COMPS, 0, 1)

## PCA Visualization 2

In [12]:
vis_pcs(DCM, 1, 2)

In [13]:
vis_loadings(COMPS, 1, 2)

# LDA Models

In [14]:
# importing the necessary packages 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation as LDA, NMF 
from sklearn.feature_extraction import text

In [15]:
# first going to read in corpus data frame 
OHCO = ['mag_id', 'page_num','token_num']
SENTENCE = OHCO[:2],
MAGAZINE = OHCO[:1]
BAG = MAGAZINE
TOKENS = pd.read_csv('/Users/aniyahmcwilliams/Spring 2026/Text As Data/final project/DATA/CORPUS.csv', index_col=['mag_id','page_num','token_num'])
TOKENS.head()

                          pos pos_group token_str term_str
mag_id page_num token_num
0      1        0          DT        DT       The      the
                1          NN        NN      text     text
                2          IN        IN        on       on
                3          DT        DT      this     this
                4          NN        NN      page     page

In [16]:
# converting the tokens table back to DOC style
DOCS = TOKENS[TOKENS.pos.str.match(r'^NNS?$')]\
    .groupby(BAG).term_str\
    .apply(lambda x: ' '.join(map(str,x)))\
    .to_frame()\
    .rename(columns={'term_str':'doc_str'})

# Creating the Vector Space

In [17]:
my_stop_words = list(text.ENGLISH_STOP_WORDS.union(['yes']))

In [18]:
count_engine = CountVectorizer(
    stop_words='english',
    max_df=0.5,
    min_df=4,
)
count_model = count_engine.fit_transform(DOCS.doc_str)
TERMS = count_engine.get_feature_names_out()
VOCAB = pd.DataFrame(index=TERMS)
VOCAB.index.name = 'term_str'
DTM = pd.DataFrame(count_model.toarray(), index=DOCS.index, columns=TERMS)
DTM

,ability,abortion,absence,accident,account,accurate,achievement,activist,administrator,advertising,...,whiskey,win,window,winter,witnesses,workers,works,worth,yearold,youth
mag_id,,,,,,,,,,,,,,,,,,,,,
0,3,0,0,0,2,2,2,1,1,1,...,0,1,0,1,0,3,0,1,1,0
1,1,0,1,0,0,1,2,0,0,0,...,0,1,7,0,0,2,1,0,0,0
2,0,1,1,0,2,0,1,1,0,1,...,1,3,0,0,1,0,0,0,0,0
3,1,0,0,0,0,3,0,1,1,0,...,0,0,0,1,0,1,0,0,0,3
4,1,1,0,2,2,0,2,1,0,2,...,0,0,0,0,1,0,1,0,1,4
5,0,2,0,0,1,1,1,0,0,0,...,3,1,1,1,1,0,1,1,0,0
6,0,0,1,3,1,0,0,0,0,1,...,1,0,0,0,0,3,0,3,0,5
7,0,0,0,2,0,0,0,0,2,0,...,0,0,0,1,2,0,0,0,1,3
8,1,1,1,2,0,0,0,0,1,2,...,1,0,2,0,0,0,0,0,1,4
9,0,0,1,2,0,1,0,0,1,0,...,0,0,2,0,1,2,1,1,0,0

# Generating the Model

In [19]:
n_topics = 5
max_iter = 1000
n_top_terms = 10
TNAMES = [f"T{str(x).zfill(len(str(n_topics)))}" for x in range(n_topics)]
topic_engine = LDA(n_components=n_topics, max_iter=max_iter, random_state=42)
topic_model = topic_engine.fit_transform(count_model)

## Calculating THETA

In [20]:
THETA = pd.DataFrame(topic_model, index=DOCS.index, columns=TNAMES)
THETA.columns.name = 'topic_id'
THETA.sample(10).T.style.background_gradient(axis=None)

# Calculating PHI

In [21]:
PHI = pd.DataFrame(topic_engine.components_, columns=TERMS, index=TNAMES)
PHI.index.name = 'topic_id'
PHI.columns.name = 'term_str'
PHI.T.sample(10).T.style.background_gradient(axis=None)

# Getting the Topics

In [22]:
pd.set_option('display.max_colwidth', 200)
TOPICS = PHI.stack().groupby('topic_id')\
    .apply(lambda x: ' '.join(x.sort_values(ascending=False).head(n_top_terms).reset_index().term_str))\
    .to_frame('top_terms')
TOPICS

                                                                                  top_terms
topic_id
T0              cent window total negroes candidates songs aterial ceremony pennant theater
T1                           price blacks guest mayor seats pair agency loan drinking level
T2                     blacks test percent copy course celebrities youth dog sports freedom
T3         heat places changes failure establishment rumors emergency vows lawmaker absence
T4        blacks campus percent cent survey university union legislation population workers