In [1]:
# going to import the necessary packages 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.preprocessing import normalize
from sklearn.decomposition import PCA, TruncatedSVD as SVD
import plotly_express as px 
import plotly.io as pio

# Loading in the data

In [2]:
LIB = pd.read_csv('/Users/aniyahmcwilliams/Spring 2026/Text As Data/final project/DATA/LIB.csv', index_col='mag_id')
TFIDF_raw = pd.read_csv('/Users/aniyahmcwilliams/Spring 2026/Text As Data/final project/DATA/TFIDF.csv',index_col='mag_id')
TFIDF = pd.DataFrame(normalize(TFIDF_raw, norm='l2', axis=1), index=TFIDF_raw.index, columns=TFIDF_raw.columns)
TFIDF

,aa,aaf,aaron,ababa,abandoned,abandonment,abbott,abc,abclou,abcparamount,...,zoomed,zooming,zoot,zor,zs,zumwalt,zunicia,zuniga,zurich,zw
mag_id,,,,,,,,,,,,,,,,,,,,,
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.021819,0.000000,0.006568,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.021819,0.021819,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.009896,0.000000,0.000000,0.000000,0.000000,0.007486,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.014858,0.000000,0.021258,0.010142,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.021258
3,0.034972,0.022065,0.000000,0.000000,0.000000,0.000000,0.000000,0.019926,0.000000,0.000000,...,0.000000,0.022065,0.000000,0.000000,0.000000,0.000000,0.022065,0.034972,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.017678,0.022718,0.000000,...,0.000000,0.000000,0.036007,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.021334,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.019344,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.024305,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.015330,0.000000
7,0.000000,0.000000,0.027047,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.009634,0.000000
8,0.000000,0.000000,0.009623,0.000000,0.016903,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.024183,0.000000,0.000000,0.024183,0.000000,0.000000,0.000000,0.000000,0.009623,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.009300,0.000000

# PCA Models

## Generating the Document Component Matrix

In [3]:
pca_engine = PCA(n_components=5)
DCM = pd.DataFrame(pca_engine.fit_transform(TFIDF), index=TFIDF.index)
DCM.columns = ['PC{}'.format(i) for i in DCM.columns]
DCM

/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:350: RuntimeWarning: divide by zero encountered in matmul
  Q, _ = normalizer(A @ Q)
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:350: RuntimeWarning: overflow encountered in matmul
  Q, _ = normalizer(A @ Q)
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:350: RuntimeWarning: invalid value encountered in matmul
  Q, _ = normalizer(A @ Q)
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:351: RuntimeWarning: divide by zero encountered in matmul
  Q, _ = normalizer(A.T @ Q)
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:351: RuntimeWarning: overflow encountered in matmul
  Q, _ = normalizer(A.T @ Q)
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:351: RuntimeWarning: invalid value encountered in matmul
  Q, _ = normalizer(A.T @ Q)
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:355: RuntimeWarning: divide by zero encountered in matmul
  Q, _ = qr_normalizer(A @ Q)
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:355: RuntimeWarning: overflow encountered in matmul
  Q, _ = qr_normalizer(A @ Q)
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:355: RuntimeWarning: invalid value encountered in matmul
  Q, _ = qr_normalizer(A @ Q)
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:577: RuntimeWarning: divide by zero encountered in matmul
  B = Q.T @ M
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:577: RuntimeWarning: overflow encountered in matmul
  B = Q.T @ M
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:577: RuntimeWarning: invalid value encountered in matmul
  B = Q.T @ M
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:590: RuntimeWarning: divide by zero encountered in matmul
  U = Q @ Uhat
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:590: RuntimeWarning: overflow encountered in matmul
  U = Q @ Uhat
/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:590: RuntimeWarning: invalid value encountered in matmul
  U = Q @ Uhat

             PC0       PC1       PC2       PC3       PC4
mag_id
0       0.266477  0.274879  0.244076 -0.381978  0.091360
1       0.108436  0.561769  0.330515  0.539125  0.162554
2       0.334209 -0.108963 -0.046076 -0.471029  0.458573
3       0.449811 -0.228586 -0.190436  0.134150 -0.369947
4       0.376961 -0.141726 -0.249879  0.272159 -0.177833
5      -0.227336 -0.549309  0.676278  0.037572 -0.130730
6      -0.352889  0.310087 -0.015282 -0.281249 -0.296676
7      -0.343959 -0.080929 -0.349447  0.053916  0.158583
8      -0.294330  0.147320 -0.188503 -0.149997 -0.373646
9      -0.317378 -0.184543 -0.211246  0.247330  0.477763

The number of components is 5.

# Component Term Matrix

In [4]:
COMPS = pd.DataFrame(pca_engine.components_.T * np.sqrt(pca_engine.explained_variance_))
COMPS.columns = ["PC{}".format(i) for i in COMPS.columns]
COMPS.index = TFIDF.columns
COMPS.index.name = 'term_str'
COMPS.T

term_str,aa,aaf,aaron,ababa,abandoned,abandonment,abbott,abc,abclou,abcparamount,...,zoomed,zooming,zoot,zor,zs,zumwalt,zunicia,zuniga,zurich,zw
PC0,0.005190,0.003274,-0.005902,-0.001600,-0.000003,0.001918,0.002344,0.007119,0.002825,-0.002830,...,-0.002348,0.003274,0.004478,-0.002348,0.001918,0.001918,0.003274,0.005190,-0.004786,0.002344
PC1,-0.002755,-0.001738,0.003717,-0.004039,0.000300,0.002067,-0.000798,-0.000743,-0.001110,0.002597,...,0.001228,-0.001738,-0.001759,0.001228,0.002067,0.002067,-0.001738,-0.002755,0.001267,-0.000798
PC2,-0.002303,-0.001453,-0.002866,0.004988,-0.001338,0.001841,-0.000339,-0.001591,-0.001963,-0.000128,...,-0.001576,-0.001453,-0.003111,-0.001576,0.001841,0.001841,-0.001453,-0.002303,-0.002551,-0.000339
PC3,0.001633,0.001030,-0.000032,0.000279,-0.003318,-0.002900,-0.003484,0.001473,0.002152,-0.002379,...,-0.001262,0.001030,0.003410,-0.001262,-0.002900,-0.002900,0.001030,0.001633,-0.001021,-0.003484
PC4,-0.004517,-0.002850,-0.001200,-0.000974,0.000174,0.000696,0.003403,-0.001413,-0.001410,-0.002517,...,-0.003155,-0.002850,-0.002235,-0.003155,0.000696,0.000696,-0.002850,-0.004517,-0.000759,0.003403

### Getting the top 5 positive and negative terms

In [5]:
top_terms_sk = {}
data = []
for i in range(5):
    for j in [0, 1]:
        data.append((i, j, ' '.join(COMPS.sort_values(f'PC{i}', ascending=bool(j)).head(10).index.to_list())))
comp_strs = pd.DataFrame(data)
comp_strs.columns =  ['pc', 'pole', 'gloss']
comp_strs = comp_strs.set_index(['pc', 'pole'])
comp_strs.unstack()

                                                  gloss  \
pole                                                  0
pc
0     blacks reggie ali mg ms hurley percent granada...
1     bavasi tornado edgerton supremes weston witch ...
2     jelly suicides dressen cicero pichon ethiopian...
3     bavasi tornado edgerton wills kodak weston ger...
4     granada tito cerda sx deedee ashe khalilah taj...


pole                                                  1
pc
0     dinah satchel lunch wealthy ark mccollum doby ...
1     jelly dressen suicides mccarthy manson pichon ...
2     mccollum ye collie nkrumah doby insane bassey ...
3     granada sx deedee ashe tolbert taj khalilah ne...
4     dinah reggie hurley bodenheimer hula hawaiian ...

# PCA Visualization 1: first two components

In [6]:
LIB

,epub_id,date,pages,month,quarter,page_num,title,character_len
mag_id,,,,,,,,
0,vo8DAAAAMBAJ,1972-12-07,"[""\n\n\n\nThis book was produced in EPUB forma...",12,4th Quarter,68,What Dope Arrest is Doing to Career of Barbara...,99374
1,ProDAAAAMBAJ,1967-05-11,"[""\n\n\n\nThis book was produced in EPUB forma...",5,2nd Quarter,68,What's Behind Suicide of Charles Diggs Sr.?,74986
2,dEIDAAAAMBAJ,1975-11-20,"[""\n\n\n\nThis book was produced in EPUB forma...",11,4th Quarter,68,Tito Jackson: His Music and His Family,89009
3,YEIDAAAAMBAJ,1978-05-04,"[""\n\n\n\nThis book was produced in EPUB forma...",5,2nd Quarter,68,New Reggie Defends His Hero Image,85341
4,AMADAAAAMBAJ,1978-07-06,"[""\n\n\n\nThis book was produced in EPUB forma...",7,3rd Quarter,68,Benson Shares His Fame With Family,89396
5,JEMDAAAAMBAJ,1951-11-01,"[""\n\n\n\nThis book was produced in EPUB forma...",11,4th Quarter,68,Ten Ways to Get a Mink Coat/ Why Negro Suicide...,81741
6,vq8DAAAAMBAJ,1960-03-10,"[""\n\n\n\nThis book was produced in EPUB forma...",3,1st Quarter,68,How Negroes Feel about a Catholic for US Presi...,79252
7,fbcDAAAAMBAJ,1958-02-20,"[""\n\n\n\nThis book was produced in EPUB forma...",2,1st Quarter,68,Rudy McCollum Talks Ends 5-Year Silence in Ins...,74909
8,YkEDAAAAMBAJ,1959-08-20,"[""\n\n\n\nThis book was produced in EPUB forma...",8,3rd Quarter,68,First Poll Reveals Candidates Negroes Want for...,78302
9,mEEDAAAAMBAJ,1959-04-09,"[""\n\n\n\nThis book was produced in EPUB forma...",4,2nd Quarter,68,Why Cuban Rebels Jailed Son of Wealthy Negro /...,76401

In [9]:
def vis_pcs(DCM, a, b, label = 'quarter', hover_name='title'):
    return px.scatter(DCM, f"PC{a}", f"PC{b}",  
                    color=LIB[label],
                    hover_name=LIB[hover_name], 
                    size=LIB['character_len'],
                    marginal_x='box', height=800)
    
def vis_loadings(COMPS, a=0, b=1, hover_name='term_str'):
    return px.scatter(COMPS.reset_index(), f"PC{a}", f"PC{b}", 
                      text='term_str', 
                      marginal_x='box', 
                      height=800)

In [10]:
vis_pcs(DCM, 0, 1)

In [11]:
vis_loadings(COMPS, 0, 1)

# PCA Visualization 2

In [12]:
vis_pcs(DCM, 1, 2)

In [13]:
vis_loadings(COMPS, 1, 2)

# LDA Models

In [22]:
# importing the necessary packages 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation as LDA, NMF 
from sklearn.feature_extraction import text

In [18]:
# first going to read in corpus data frame 
OHCO = ['mag_id', 'page_num','token_num']
SENTENCE = OHCO[:2],
MAGAZINE = OHCO[:1]
BAG = MAGAZINE
TOKENS = pd.read_csv('/Users/aniyahmcwilliams/Spring 2026/Text As Data/final project/DATA/CORPUS.csv', index_col=['mag_id','page_num','token_num'])
TOKENS.head()

                          pos pos_group token_str term_str
mag_id page_num token_num
0      1        0          DT        DT       The      the
                1          NN        NN      text     text
                2          IN        IN        on       on
                3          DT        DT      this     this
                4          NN        NN      page     page

In [20]:
# converting the tokens table back to DOC style
DOCS = TOKENS[TOKENS.pos.str.match(r'^NNS?$')]\
    .groupby(BAG).term_str\
    .apply(lambda x: ' '.join(map(str,x)))\
    .to_frame()\
    .rename(columns={'term_str':'doc_str'})
DOCS

                                                  doc_str
mag_id
0       text page kl ll ll warning jmgsr jvm editor ph...
1       kissiri cousin friendship taste goodbye flfi w...
2       elevator pack pack editor photo story page off...
3       tar lot air coolness coolness kind refreshment...
4       taste smoke taste taste cigarette doesn taste ...
5       role night show year farm ess indictments negr...
6       graduate opinions whiz kid basketball records ...
7       model styles swim suits news pictures week wee...
8       lawyer state message brilliant leader message ...
9       week mail issues words widow man guests honor ...

# Creating the Vector Space

In [23]:
my_stop_words = list(text.ENGLISH_STOP_WORDS.union(['yes']))

In [ ]:
count_engine = CountVectorizer(max_df=.8,min_df=,stop_words=my_stop_words)
count_model = count_engine.fit_transform(DOCS.doc_str)
TERMS = count_engine.get_feature_names_out()
VOCAB = pd.DataFrame(index=TERMS)
VOCAB.index.name = 'term_str'
DTM = pd.DataFrame(count_model.toarray(), index=DOCS.index, columns=TERMS)
DTM

,abandonment,abdomen,abiding,ability,aboardship,abolitionist,abortion,aboutface,abreast,absence,...,younger,youngster,youngsters,youth,youths,zenith,zip,zone,zoo,zw
mag_id,,,,,,,,,,,,,,,,,,,,,
0,1,0,0,3,0,0,0,0,0,0,...,0,0,0,0,3,0,1,0,0,0
1,0,0,1,1,0,0,0,0,0,1,...,0,1,2,0,0,0,0,0,0,0
2,0,0,0,0,0,0,1,0,1,1,...,0,1,0,0,3,0,0,0,1,1
3,0,0,0,1,0,0,0,0,0,0,...,1,1,1,3,1,0,0,0,0,0
4,0,0,0,1,0,0,1,0,0,0,...,0,0,1,4,0,0,0,0,0,0
5,0,0,0,0,0,1,2,0,0,0,...,0,0,0,0,1,0,0,0,0,0
6,0,1,0,0,0,0,0,1,0,1,...,0,0,1,5,2,1,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,1,3,0,0,0,0,0,0
8,0,0,0,1,1,0,1,0,0,1,...,0,0,2,4,4,0,0,1,0,0
9,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,3,0,0,0,0,0