In [1]:
# importing necessary packages 
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.io as pio
from gensim.corpora import Dictionary
from gensim.models import word2vec
from sklearn.manifold import TSNE as tsne

In [3]:
TOKENS = pd.read_csv('/Users/aniyahmcwilliams/Spring 2026/Text As Data/final project/DATA/CORPUS.csv', index_col=['mag_id','page_num','token_num'])
TOKENS

                           pos pos_group token_str  term_str
mag_id page_num token_num
0      1        0           DT        DT       The       the
                1           NN        NN      text      text
                2           IN        IN        on        on
                3           DT        DT      this      this
                4           NN        NN      page      page
...                        ...       ...       ...       ...
9      68       55         NNP        NN      INC.       inc
                57         NNP        NN  Michigan  michigan
                58         NNP        NN    Avenue    avenue
                60         NNP        NN   Chicago   chicago
                62         NNP        NN  Illinois  illinois

[131948 rows x 4 columns]

In [4]:
# need to exclude proper nouns from the table 
TOKENS = TOKENS[TOKENS['pos'] != 'NNP']
TOKENS = TOKENS[TOKENS['pos'] != 'NNPS']
TOKENS

                          pos pos_group   token_str    term_str
mag_id page_num token_num
0      1        0          DT        DT         The         the
                1          NN        NN        text        text
                2          IN        IN          on          on
                3          DT        DT        this        this
                4          NN        NN        page        page
...                        ..       ...         ...         ...
9      68       43         NN        NN  popularity  popularity
                45         CC        CC       write       write
                46         NN        NN       today       today
                47         IN        IN         for         for
                48         JJ        JJ     Special     special

[99929 rows x 4 columns]

## Converting to Genism

In [ ]:
docs = TOKENS.groupby('mag_id').term_str.apply(list).tolist()
# for i in range(5):
#     print(f"Magazine {i}:", docs[i])

Magazine 0: ['the', 'text', 'on', 'this', 'page', 'is', 'estimated', 'to', 'be', 'only', 'accurate', 'nrwt', 'ii', 'kl', 'll', 'll', 'warning', 'the', 'determined', 'that', 'is', 'dangerous', 'to', 'your', 'and', 'jmgsr', 'jvm', 'editor', 'and', 'photo', 'by', 'and', 'of', 'story', 'on', 'page', 'african', 'and', 'and', 'people', 'people', 'are', 'talking', 'about', 'politics', 'readers', 'of', 'the', 'weekly', 'by', 'office', 'at', 'of', 'the', 'office', 'secondclass', 'postage', 'paid', 'at', 'by', 'one', 'year', 'foreign', 'we', 'can', 'not', 'be', 'responsible', 'for', 'unsolicited', 'material', 'of', 'readers', 'discussed', 'regarding', 'your', 'story', 'on', 'recalled', 'the', 'many', 'articles', 'which', 'have', 'read', 'on', 'the', 'super', 'star', 'and', 'none', 'really', 'tell', 'where', 'he', 'lived', 'and', 'how', 'his', 'first', 'single', 'became', 'mild', 'hit', 'maybe', 'green', 'doesn', 'want', 'anyone', 'to', 'know', 'that', 'he', 'is', 'from', 'and', 'his', 'family', 'still', 'lives', 'here', 'very', 'fine', 'promoter', 'by', 'the', 'name', 'of', 'of', 'wrote', 'and', 'produced', 'for', 'and', 'after', 'the', 'release', 'of', 'that', 'recording', 'left', 'where', 'he', 'grew', 'up', 'and', 'went', 'to', 'school', 'and', 'has', 'only', 'returned', 'twice', 'since', 'then', 'moved', 'to', 'when', 'he', 'was', 'nine', 'he', 'moved', 'to', 'years', 'later', 'and', 'has', 'remained', 'there', 'since', 'wept', 'when', 'died', 'when', 'read', 'your', 'article', 'on', 'wept', 'the', 'man', 'was', 'so', 'strong', 'where', 'he', 'found', 'the', 'strength', 'to', 'carry', 'on', 'the', 'burden', 'of', 'being', 'the', 'only', 'in', 'the', 'baseball', 'game', 'we', 'll', 'never', 'know', 'weaker', 'man', 'would', 'have', 'given', 'up', 'after', 'the', 'threats', 'started', 'to', 'come', 'in', 'the', 'mail', 'but', 'then', 'was', 'no', 'ordinary', 'man', 'he', 'was', 'giant', 'robinson', 'monument', 'editor', 'you', 'for', 'your', 'coverage', 'of', 'both', 'life', 'and', 'death', 'it', 'was', 'very', 'heart', 'warming', 'his', 'dedication', 'to', 'the', 'game', 'of', 'baseball', 'and', 'his', 'true', 'contributions', 'to', 'humanity', 'should', 'always', 'be', 'remembered', 'by', 'our', 'race', 'he', 'was', 'another', 'of', 'our', 'great', 'guided', 'missiles', 'that', 'could', 'not', 'be', 'exploded', 'by', 'manmade', 'devices', 'or', 'freak', 'of', 'nature', 'because', 'of', 'refusal', 'to', 'accept', 'life', 'as', 'it', 'is', 'he', 'was', 'truly', 'monument', 'within', 'himself', 'questioned', 'have', 'been', 'reading', 'magazine', 'regularly', 'since', 'moved', 'to', 'this', 'small', 'town', 'of', 'as', 'blackoriented', 'literature', 'is', 'very', 'hard', 'to', 'come', 'by', 'am', 'very', 'disappointed', 'that', 'blacks', 'are', 'still', 'writing', 'about', 'how', 'shocked', 'and', 'offended', 'they', 'feel', 'as', 'result', 'of', 'police', 'brutality', 'and', 'denials', 'of', 'civil', 'rights', 'for', 'our', 'people', 'am', 'equally', 'annoyed', 'at', 'the', 'feeling', 'of', 'progress', 'many', 'blacks', 'feel', 'when', 'other', 'blacks', 'are', 'placed', 'in', 'powerless', 'token', 'positions', 'the', 'situation', 'has', 'been', 'the', 'same', 'for', 'centuries', 'in', 'this', 'country', 'we', 'have', 'been', 'in', 'long', 'enough', 'to', 'know', 'that', 'double', 'standard', 'of', 'law', 'and', 'justice', 'for', 'and', 'whites', 'definitely', 'exists', 'jet', 'wul', 'consider', 'for', 'publication', 'only', 'letters', 'with', 'names', 'and', 'addresses', 'letters', 'to', 'can', 'not', 'be', 'returned', 'or', 'acknowledged', 'and', 'are', 'subject', 'to', 'editing', 'ousts', 'two', 'members', 'according', 'to', 'diplomatic', 'sources', 'two', 'new', 'cabinet', 'members', 'took', 'office', 'recently', 'following', 'ier', 'dismissal', 'of', 'in', 'was', 'relieved', 'of', 'his', 'posts', 'as', 'minister', 'of', 'the', 'interior', 'and', 'minister', 'of', 'defense', 'in', 'what', 'was', 'the', 'first', 'cabinet', 'shakeup', 'since', 'the', 'president', 'took', 'office', 'following', 'the', 'death', 'of', 'his', 'father', 'months', 'ago', 'was', 'installed', 'in', 'place', 'in', 'both', 'key', 'ministries', 'he', 'is', 'described', 'by', 'diplomatic', 'sources', 'as', 'relatively', 'unknown', 'figure', 'who', 'was', 'previously', 'consul', 'general', 'in', 'took', 'over', 'in', 'the', 'of', 'succeeding', 'to', 'federal', 'judge', 'recently', 'told', 'the', 'of', 'and', 'to', 'cut', 'off', 'federal', 'money', 'to', 'school', 'districts', 'still', 'practicing', 'racial', 'segregation', 'in', 'written', 'opinion', 'ruled', 'that', 'efforts', 'made', 'by', 'and', 'the', 'department', 'of', 'toward', 'voluntary', 'compliance', 'with', 'the', 'have', 'been', 'unsuccessful', 'in', 'the', 'case', 'of', 'many', 'state', 'and', 'local', 'educational', 'agencies', 'which', 'in', 'recently', 'named', 'the', 'as', 'auxiliary', 'bishop', 'of', 'the', 'diocese', 'of', 'making', 'him', 'the', 'second', 'bishop', 'in', 'history', 'before', 'appointment', 'the', 'hierarchy', 'of', 'bishops', 'had', 'only', 'one', 'prelate', 'the', 'of', 'the', 'to', 'which', 'has', 'been', 'appointed', 'has', 'catholics', 'percent', 'of', 'whom', 'are', 'born', 'in', 'graduated', 'from', 'in', 'and', 'taught', 'biology', 'he', 'converted', 'to', 'and', 'later', 'decided', 'to', 'enter', 'the', 'priesthood', 'superior', 'the', 'said', 'that', 'million', 'live', 'in', 'and', 'added', 'that', 'there', 'are', 'more', 'blacks', 'within', 'mile', 'radius', 'of', 'than', 'in', 'any', 'other', 'comparable', 'area', 'in', 'the', 'world', 'it', 'will', 'bring', 'new', 'courage', 'to', 'our', 'apostolate', 'in', 'said', 'particularly', 'among', 'the', 'population', 'continue', 'to', 'receive', 'federal', 'funds', 'in', 'violation', 'of', 'the', 'statue', 'wrote', 'that', 'attempt', 'at', 'gaining', 'voluntary', 'compliance', 'has', 'been', 'unsuccessful', 'or', 'has', 'met', 'with', 'rejection', 'by', 'public', 'colleges', 'and', 'universities', 'in', 'and', 'two', 'law', 'enforcement', 'officers', 'watch', 'as', 'tear', 'gas', 'shells', 'explode', 'on', 'lawn', 'in', 'front', 'of', 'administration', 'building', 'in', 'for', 'at', 'to', 'many', 'it', 'was', 'the', 'inevitable', 'result', 'of', 'institutional', 'racism', 'to', 'others', 'it', 'was', 'the', 'inevitable', 'result', 'of', 'the', 'unthinking', 'militancy', 'born', 'of', 'the', 'institutional', 'racisms', 'of', 'people', 'getting', 'out', 'of', 'their', 'place', 'in', 'whitedominated', 'society', 'to', 'of', 'and', 'to', 'of', 'both', 'the', 'cause', 'made', 'little', 'difference', 'their', 'lives', 'and', 'dreams', 'were', 'shattered', 'by', 'buckshot', 'pellets', 'both', 'and', 'were', 'students', 'at', 'in', 'the', 'campus', 'and', 'its', 'sister', 'campus', 'in', 'had', 'been', 'the', 'scenes', 'of', 'tense', 'but', 'mostly', 'nonviolent', 'student', 'demonstrations', 'for', 'several', 'weeks', 'who', 'killed', 'and', 'has', 'not', 'been', 'established', 'however', 'there', 'is', 'strong', 'belief', 'supported', 'by', 'circumstantial', 'evidence', 'that', 'the', 'fatal', 'shot', 'or', 'shots', 'came', 'from', 'one', 'or', 'more', 'sheriff', 'deputies', 'who', 'were', 'called', 'to', 'the', 'campus', 'generally', 'agreed', 'upon', 'version', 'of', 'what', 'happened', 'on', 'the', 'morning', 'of', 'when', 'and', 'were', 'killed', 'follows', 'nearly', 'students', 'who', 'had', 'been', 'part', 'of', 'student', 'crowd', 'of', 'persons', 'were', 'standing', 'in', 'front', 'of', 'the', 'administration', 'building', 'when', 'an', 'estimated', 'armed', 'lawmen', 'arrived', 'on', 'the', 'campus', 'number', 'of', 'the', 'students', 'had', 'gone', 'to', 'the', 'building', 'to', 'speak', 'with', 'president', 'of', 'the', 'system', 'about', 'the', 'arrests', 'of', 'several', 'student', 'leaders', 'who', 'had', 'coordinated', 'the', 'protest', 'whose', 'resignation', 'has', 'been', 'called', 'for', 'by', 'the', 'protesting', 'students', 'and', 'some', 'faculty', 'members', 'on', 'both', 'campuses', 'left', 'his', 'office', 'when', 'the', 'students', 'arrived', 'the', 'students', 'began', 'placing', 'temporarily', 'closed', 'signs', 'around', 'the', 'administration', 'building', 'and', 'littered', 'the', 'president', 'office', 'they', 'moved', 'outside', 'the', 'building', 'the', 'lawmen', 'gathered', 'in', 'front', 'of', 'the', 'building', 'speaking', 'from', 'an', 'armored', 'vehicle', 'issued', 'garbled', 'warning', 'to', 'the', 'students', 'standing', 'in', 'front', 'of', 'the', 'building', 'to', 'leave', 'the', 'students', 'remained', 'someone', 'threw', 'smoking', 'canister', 'police', 'said', 'it', 'came', 'from', 'the', 'students', 'and', 'the', 'lawmen', 'began', 'firing', 'tear', 'gas', 'the', 'sounds', 'of', 'the', 'exploding', 'tear', 'gas', 'shells', 'mixed', 'with', 'the', 'screams', 'of', 'the', 'fleeing', 'students', 'it', 'lasted', 'minutes', 'when', 'the', 'commotion', 'was', 'over', 'and', 'were', 'dead', 'the', 'sheriff', 'deputies', 'were', 'fice', 'are', 'made', 'in', 'the', 'same', 'size', 'and', 'color', 'as', 'regular', 'shotgun', 'shells', 'and', 'are', 'fired', 'from', 'shotguns', 'he', 'added', 'that', 'the', 'deputies', 'were', 'scared', 'to', 'death', 'and', 'poorly', 'trained', 'for', 'such', 'confrontation', 'southern', 'campus', 'was', 'closed', 'until', 'after', 'the', 'holidays', 'as', 'result', 'of', 'the', 'incident', 'the', 'real', 'trouble', 'at', 'began', 'in', 'when', 'bodies', 'of', 'two', 'slain', 'students', 'lay', 'sprawled', 'in', 'pools', 'of', 'blood', 'videotapes', 'of', 'the', 'shooting', 'indicated', 'that', 'both', 'students', 'were', 'killed', 'by', 'the', 'same', 'shot', 'gun', 'blast', 'armed', 'with', 'the', 'approximate', 'caliber', 'of', 'weapons', 'no', 'buckshot', 'that', 'killed', 'the', 'two', 'students', 'said', 'later', 'that', 'he', 'had', 'no', 'doubt', 'it', 'was', 'blast', 'of', 'buckshot', 'mistakenly', 'fired', 'by', 'deputy', 'sheriff', 'that', 'killed', 'the', 'young', 'men', 'the', 'governor', 'explained', 'that', 'the', 'tear', 'gas', 'shells', 'used', 'by', 'the', 'sheriff', 'ofthe', 'school', 'was', 'established', 'under', 'laws', 'by', 'an', 'allwhite', 'state', 'legislature', 'like', 'other', 'state', 'institutions', 'established', 'by', 'whites', 'to', 'keep', 'the', 'niggers', 'in', 'their', 'place', 'the', 'school', 'has', 'nearly', 'always', 'been', 'separate', 'from', 'but', 'very', 'seldom', 'equal', 'to', 'the', 'white', 'state', 'colleges', 'and', 'universities', 'in', 'terms', 'of', 'funding', 'and', 'plant', 'facilities', 'iterlal', 'but', 'in', 'many', 'blacks', 'were', 'happy', 'to', 'receive', 'any', 'kind', 'of', 'education', 'albeit', 'unequal', 'also', 'at', 'that', 'time', 'administrators', 'of', 'allblack', 'state', 'schools', 'were', 'chosen', 'not', 'so', 'much', 'for', 'their', 'ability', 'to', 'further', 'higher', 'education', 'as', 'they', 'were', 'for', 'their', 'ability', 'to', 'get', 'along', 'with', 'white', 'politicians', 'who', 'controlled', 'the', 'schools', 'times', 'have', 'changed', 'and', 'so', 'has', 'the', 'caliber', 'of', 'college', 'students', 'but', 'other', 'than', 'the', 'meager', 'increase', 'of', 'eight', 'in', 'serving', 'in', 'state', 'legislatures', 'what', 'changes', 'have', 'taken', 'place', 'in', 'the', 'minds', 'of', 'white', 'politicians', 'what', 'changes', 'have', 'administrators', 'of', 'predominantlyblack', 'state', 'colleges', 'undergone', 'protesting', 'students', 'at', 'charged', 'that', 'no', 'changes', 'have', 'taken', 'place', 'in', 'the', 'racial', 'attitudes', 'of', 'the', 'white', 'lawmakers', 'who', 'allocate', 'state', 'funds', 'and', 'that', 'in', 'the', 'case', 'of', 'university', 'administrators', 'few', 'changes', 'have', 'taken', 'place', 'so', 'in', 'when', 'young', 'psychology', 'instructor', 'who', 'was', 'popular', 'among', 'the', 'students', 'resigned', 'the', 'students', 'seized', 'the', 'opportunity', 'to', 'press', 'their', 'grievances', 'they', 'charged', 'that', 'the', 'allwhite', 'of', 'was', 'shortchanging', 'the', 'state', 'colleges', 'that', 'they', 'needed', 'better', 'housing', 'better', 'classroom', 'facilities', 'stronger', 'academic', 'departments', 'better', 'food', 'and', 'voice', 'in', 'administration', 'affairs', 'they', 'demanded', 'that', 'resign', 'the', 'students', 'on', 'campus', 'began', 'class', 'boycott', 'to', 'dramatize', 'their', 'demands', 'at', 'which', 'time', 'ordered', 'the', 'campus', 'closed', 'for', 'coolingoff', 'period', 'several', 'days', 'passed', 'the', 'campus', 'reopened', 'and', 'most', 'of', 'the', 'students', 'returned', 'to', 'classes', 'but', 'the', 'unrest', 'that', 'began', 'on', 'the', 'campus', 'populated', 'by', 'students', 'spilled', 'onto', 'campus', 'and', 'sparked', 'sometimes', 'violent', 'demonstrations', 'at', 'there', 'were', 'student', 'arrests', 'at', 'after', 'the', 'crisis', 'ended', 'it', 'was', 'generally', 'felt', 'that', 'tensions', 'would', 'subside', 'and', 'that', 'all', 'remaining', 'boycotting', 'students', 'would', 'return', 'to', 'their', 'classes', 'the', 'feeling', 'was', 'enhanced', 'by', 'several', 'reported', 'understandings', 'reached', 'by', 'students', 'and', 'administrators', 'on', 'the', 'campus', 'among', 'the', 'understandings', 'were', 'included', 'amnesty', 'from', 'legal', 'action', 'against', 'protesting', 'students', 'and', 'an', 'alleged', 'agreement', 'that', 'would', 'not', 'seek', 'another', 'two', 'year', 'extension', 'of', 'his', 'term', 'is', 'working', 'under', 'contract', 'that', 'extends', 'his', 'tenure', 'until', 'next', 'past', 'the', 'normal', 'retirement', 'age', 'of', 'he', 'has', 'been', 'president', 'of', 'the', 'university', 'system', 'for', 'four', 'years', 'and', 'major', 'power', 'in', 'the', 'operation', 'of', 'the', 'university', 'for', 'more', 'than', 'years', 'in', 'his', 'first', 'public', 'appearance', 'two', 'days', 'after', 'the', 'shootings', 'reponded', 'to', 'questions', 'concerning', 'his', 'resignation', 'saying', 'the', 'charges', 'were', 'false', 'and', 'irresponsible', 'asked', 'if', 'he', 'would', 'seek', 'an', 'extension', 'of', 'his', 'term', 'he', 'said', 'will', 'make', 'that', 'decision', 'when', 'the', 'time', 'comes', 'the', 'time', 'may', 'be', 'coming', 'soon', 'although', 'has', 'publicly', 'supported', 'he', 'has', 'indicated', 'that', 'he', 'would', 'welcome', 'resignation', 'next', 'summer', 'the', 'governor', 'who', 'got', 'into', 'office', 'because', 'of', 'large', 'vote', 'said', 'that', 'is', 'out', 'of', 'touch', 'with', 'his', 'students', 'and', 'much', 'of', 'his', 'faculty', 'white', 'man', 'and', 'is', 'man', 'but', 'come', 'closer', 'to', 'understanding', 'those', 'students', 'than', 'he', 'does', 'said', 'other', 'casualties', 'of', 'the', 'disturbances', 'were', 'two', 'teachers', 'and', 'who', 'were', 'dismissed', 'the', 'day', 'after', 'the', 'shooting', 'was', 'terminated', 'because', 'had', 'acted', 'as', 'an', 'advisor', 'to', 'the', 'dissident', 'students', 'said', 'an', 'assistant', 'professor', 'of', 'engineering', 'said', 'the', 'students', 'wanted', 'the', 'university', 'to', 'begin', 'dealing', 'with', 'the', 'community', 'but', 'the', 'university', 'did', 'not', 'want', 'to', 'physics', 'teacher', 'was', 'also', 'dismissed', 'because', 'of', 'his', 'involvement', 'with', 'the', 'students', 'the', 'shooting', 'has', 'come', 'under', 'scrutiny', 'by', 'the', 'of', 'at', 'the', 'request', 'of', 'the', 'of', 'the', 'incident', 'marked', 'the', 'third', 'time', 'since', 'that', 'collegians', 'in', 'the', 'were', 'killed', 'in', 'demonstrations', 'by', 'predominantlywhite', 'group', 'of', 'law', 'enforcement', 'officers', 'on', 'at', 'state', 'troopers', 'killed', 'three', 'students', 'and', 'wounded', 'others', 'during', 'protests', 'against', 'the', 'operation', 'of', 'segregated', 'bowling', 'alley', 'near', 'campus', 'on', 'two', 'youths', 'were', 'killed', 'and', 'others', 'injured', 'during', 'policestudent', 'confrontation', 'at', 'this', 'one', 'walks', 'through', 'campus', 'with', 'armed', 'plainclothes', 'guard', 'of', 'attended', 'in', 'he', 'entered', 'the', 'business', 'in', 'he', 'was', 'employed', 'by', 'in', 'and', 'was', 'promoted', 'to', 'in', 'he', 'and', 'wife', 'reside', 'in', 'finished', 'and', 'in', 'she', 'was', 'employed', 'by', 'in', 'and', 'since', 'that', 'time', 'she', 'has', 'served', 'as', 'and', 'now', 'attended', 'he', 'entered', 'the', 'business', 'in', 'became', 'with', 'in', 'he', 'has', 'completed', 'is', 'an', 'eligible', 'bachelor', 'to', 'be', 'named', 'of', 'the', 'is', 'coveted', 'honor', 'sought', 'after', 'by', 'all', 'of', 'representatives', 'selected', 'is', 'testimony', 'to', 'dedicated', 'service', 'and', 'sales', 'ability', 'has', 'sales', 'openings', 'for', 'men', 'and', 'women', 'in', 'and', 'the', 'following', 'states', 'and', 'by', 'the', 'question', 'is', 'whether', 'the', 'top', 'advisor', 'for', 'in', 'the', 'campaign', 'and', 'can', 'line', 'up', 'enough', 'support', 'to', 'block', 'the', 'overthrow', 'of', 'at', 'the', 'meeting', 'in', 'and', 'laborites', 'are', 'leading', 'the', 'movement', 'blacks', 'however', 'are', 'credited', 'with', 'giving', 'percent', 'of', 'their', 'election', 'vote', 'to', 'the', 'but', 'southerners', 'who', 'control', 'many', 'of', 'the', 'committees', 'are', 'also', 'demanding', 'an', 'abandonment', 'of', 'the', 'reform', 'program', 'in', 'the', 'party', 'as', 'price', 'for', 'their', 'vote', 'committee', 'fight', 'over', 'could', 'force', 'blacks', 'and', 'southerners', 'into', 'confrontation', 'but', 'lawmakers', 'have', 'not', 'been', 'vocal', 'up', 'to', 'this', 'point', 'admiral', 'courageous', 'oneman', 'effort', 'to', 'right', 'the', 'racial', 'posture', 'in', 'the', 'is', 'deserving', 'of', 'recognition', 'especially', 'during', 'these', 'times', 'when', 'so', 'many', 'blacks', 'feel', 'that', 'little', 'can', 'be', 'done', 'still', 'the', 'naval', 'officer', 'strangely', 'quiet', 'now', 'and', 'since', 'his', 'promotion', 'is', 'the', 'first', 'admiral', 'in', 'the', 'has', 'made', 'an', 'input', 'in', 'the', 'racerelations', 'area', 'gravely', 'on', 'the', 'other', 'hand', 'has', 'stayed', 'as', 'far', 'away', 'from', 'the', 'troubles', 'as', 'he', 'can', 'consultant', 'on', 'of', 'problems', 'is', 'woman', 'lawyer', 'she', 'is', 'the', 'coordinator', 'for', 'the', 'problems', 'universitytrained', 'lawyer', 'and', 'one', 'who', 'is', 'expected', 'to', 'become', 'major', 'luminary', 'in', 'the', 'next', 'four', 'years', 'diplomat', 'for', 'administrator', 'for', 'was', 'named', 'one', 'of', 'the', 'awardees', 'for', 'distinguished', 'service', 'in', 'government', 'served', 'as', 'representatives', 'in', 'african', 'countries', 'supervising', 'the', 'spending', 'of', 'millions', 'of', 'dollars', 'assistant', 'suffered', 'the', 'loss', 'of', 'three', 'close', 'family', 'members', 'including', 'son', 'within', 'stretch', 'of', 'five', 'weeks', 'this', 'is', 'reason', 'he', 'has', 'not', 'been', 'involved', 'in', 'the', 'latest', 'rash', 'of', 'naval', 'discrimination', 'cases', 'protests', 'mount', 'over', 'the', 'police', 'attack', 'on', 'political', 'leader', 'arriving', 'in', 'is', 'met', 'by', 'liberian', 'of', 'and', 'of', 'head', 'party', 'included', 'ambassador', 'to', 'nd', 'to', 'by', 'with', 'their', 'arms', 'around', 'each', 'other', 'shoulders', 'of', 'and', 'the', 'president', 'of', 'to', 'walked', 'down', 'one', 'of', 'the', 'plushcarpeted', 'halls', 'of', 'this', 'west', 'african', 'nation', 'chatting', 'about', 'the', 'discussion', 'they', 'had', 'just', 'completed', 'one', 'that', 'promises', 'to', 'usher', 'in', 'an', 'entirely', 'new', 'relationship', 'between', 'and', 'have', 'absolutely', 'nothing', 'against', 'it', 'so', 'let', 'begin', 'studying', 'all', 'the', 'details', 'had', 'been', 'enthusiastic', 'response', 'to', 'proposal', 'that', 'blacks', 'be', 'granted', 'dual', 'citi

## Extract vocabulary

In [9]:
dictionary = Dictionary(docs)
dictionary

## Generating Word Embeddings

In [21]:
w2v_params = dict(
    window = 2,
    vector_size = 100,
    min_count = 25, # THIS LIMITS OUR VOCAB
    workers = 4
)

In [22]:
model = word2vec.Word2Vec(docs, **w2v_params)
model.wv.vectors

array([[-0.11116361,  0.14879623,  0.07234195, ..., -0.11253504,
        -0.05682641,  0.00954275],
       [-0.13956845,  0.16889782,  0.05354016, ..., -0.12051115,
        -0.07743851,  0.00326741],
       [-0.10400221,  0.09931282,  0.02901649, ..., -0.09494261,
        -0.09555712, -0.01172785],
       ...,
       [-0.0769724 ,  0.06115159,  0.02838993, ..., -0.06099846,
        -0.09873429, -0.00514937],
       [-0.05572275,  0.05826187,  0.01322086, ..., -0.06619602,
        -0.08180808, -0.0143179 ],
       [-0.07894122,  0.05390297,  0.02000701, ..., -0.07209023,
        -0.09371654, -0.00381032]], dtype=float32)

In [23]:
WV = pd.DataFrame(model.wv.vectors, index=model.wv.index_to_key)
WV.index.name = 'term_str'
WV

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
term_str,,,,,,,,,,,,,,,,,,,,,
the,-0.111164,0.148796,0.072342,0.221217,-0.096961,-0.453041,0.112179,0.441204,-0.259200,-0.223016,...,0.211859,0.048012,0.042461,0.031390,0.349741,0.213687,0.117057,-0.112535,-0.056826,0.009543
of,-0.139568,0.168898,0.053540,0.209348,-0.061916,-0.469744,0.121293,0.460138,-0.280049,-0.243090,...,0.203799,0.035587,0.040625,0.009337,0.313355,0.193293,0.175569,-0.120511,-0.077439,0.003267
and,-0.104002,0.099313,0.029016,0.169570,-0.068836,-0.371445,0.085844,0.390691,-0.233965,-0.143484,...,0.246745,0.051926,0.055386,0.052918,0.338773,0.231648,0.122375,-0.094943,-0.095557,-0.011728
in,-0.121550,0.129748,0.043063,0.183863,-0.066226,-0.413353,0.108203,0.415633,-0.230196,-0.194259,...,0.246074,0.043586,0.040080,0.038126,0.336433,0.209372,0.142846,-0.112944,-0.098142,-0.007254
to,-0.096134,0.081485,0.018845,0.170819,-0.053158,-0.333459,0.099150,0.370564,-0.217655,-0.101219,...,0.310803,0.050346,0.052373,0.059524,0.324704,0.223469,0.118506,-0.072448,-0.141291,-0.000528
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
college,-0.070985,0.055259,0.026298,0.119840,-0.036666,-0.244972,0.063084,0.266076,-0.160929,-0.083292,...,0.198085,0.038669,0.022220,0.049246,0.218650,0.156782,0.081107,-0.061799,-0.093526,0.000318
campus,-0.075425,0.061981,0.026304,0.126004,-0.054484,-0.264057,0.068934,0.260995,-0.156575,-0.085737,...,0.187879,0.027633,0.039328,0.045370,0.222851,0.158528,0.084392,-0.059340,-0.083213,-0.007203
born,-0.076972,0.061152,0.028390,0.134752,-0.054440,-0.256888,0.074180,0.274449,-0.150559,-0.088570,...,0.212473,0.030916,0.022877,0.056512,0.219704,0.162631,0.076506,-0.060998,-0.098734,-0.005149
paid,-0.055723,0.058262,0.013221,0.117175,-0.046753,-0.247807,0.072061,0.264757,-0.158508,-0.092087,...,0.203078,0.027152,0.039976,0.043245,0.216049,0.157198,0.081240,-0.066196,-0.081808,-0.014318
african,-0.078941,0.053903,0.020007,0.124119,-0.046811,-0.283141,0.076110,0.295429,-0.169282,-0.104929,...,0.204936,0.031502,0.036390,0.048235,0.236017,0.170189,0.070123,-0.072090,-0.093717,-0.003810

# tSNE Visualization

In [27]:
PP = 15

tsne_engine = tsne(
    perplexity=PP, 
    n_components=2, 
    init='pca', 
    max_iter=2500, 
    random_state=23
)
TSNE = pd.DataFrame(
    tsne_engine.fit_transform(WV), 
    columns=['x','y'], 
    index=WV.index)
TSNE

/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:350: RuntimeWarning:

divide by zero encountered in matmul

/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:350: RuntimeWarning:

overflow encountered in matmul

/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:350: RuntimeWarning:

invalid value encountered in matmul

/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:351: RuntimeWarning:

divide by zero encountered in matmul

/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:351: RuntimeWarning:

overflow encountered in matmul

/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:351: RuntimeWarning:

invalid value encountered in matmul

/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:355: RuntimeWarning:

divide by zero encountered in matmul

/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:355: RuntimeWarning:

overflow encountered in matmul

/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:355: RuntimeWarning:

invalid value encountered in matmul

/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:577: RuntimeWarning:

divide by zero encountered in matmul

/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:577: RuntimeWarning:

overflow encountered in matmul

/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:577: RuntimeWarning:

invalid value encountered in matmul

/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:590: RuntimeWarning:

divide by zero encountered in matmul

/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:590: RuntimeWarning:

overflow encountered in matmul

/Users/aniyahmcwilliams/miniconda3/envs/ds6021/lib/python3.12/site-packages/sklearn/utils/extmath.py:590: RuntimeWarning:

invalid value encountered in matmul

                  x          y
term_str
the      -22.972446  30.528456
of       -24.091766  30.405582
and      -28.738213  25.330706
in       -24.114258  27.399509
to       -52.326359  -6.484911
...             ...        ...
college   90.373253  -3.352135
campus    92.160866   0.820726
born      81.963188  -1.952649
paid      87.126122  -0.642433
african   73.466789  -3.549154

[486 rows x 2 columns]

In [28]:
TSNE['gid'] = TSNE.apply(lambda x: dictionary.token2id[x.name], axis=1)
TSNE['n'] = TSNE.gid.map(dictionary.cfs)
TSNE

                  x          y   gid     n
term_str
the      -22.972446  30.528456  2623  6877
of       -24.091766  30.405582  1750  3809
and      -28.738213  25.330706   115  3186
in       -24.114258  27.399509  1309  2992
to       -52.326359  -6.484911  2664  2978
...             ...        ...   ...   ...
college   90.373253  -3.352135   507    25
campus    92.160866   0.820726   382    25
born      81.963188  -1.952649   319    25
paid      87.126122  -0.642433  1830    25
african   73.466789  -3.549154    65    25

[486 rows x 4 columns]

In [29]:
px.scatter(TSNE.reset_index(), 'x', 'y', 
        text='term_str', 
        hover_name='term_str',  
        # size='n',
        height=1000,
        width=1200)\
    .update_traces(
        mode='markers+text', 
        textfont=dict(color='black', size=14, family='Arial'),
        textposition='top center')